### ISSUE TITLE
Add support for PvZ 2 10.8.1 Official 

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#17]
In the newest version (10.8.1), PopCap has added new "RESOURCES.NEWTON", toolkit should be modify to adapt the decode and encode newton function.
Additionally, ResourceConvert.ts must also be modified.

```ts                       
assert_test(resource_path_list.length === 1, `MANIFEST subgroup must has one only resource`);
```

The size of the MANIFEST now increased to 2, so toolkit should not check this anymore, instead please find the RESOURCES.RTON and call the decode RTON function through API.

Please check it yourself.

[PvZ 2 10.8.1 Resource in my Onedrive](https://msconfigs-my.sharepoint.com/:u:/g/personal/harumavn963_365_sfc_edu_vn/EQ63pu0Mrk5Fpth2ULjZVw8BSeDfFOs_r58z0_o8bCdK-w?e=bwVIsv)

**Comment by twinkles-twinstar** [comment]
A fix for ResourceConvert has been pushed.
For newton files, at present, it is meaningless to support newton encoding, because according to your test, the game reads rton first rather than newton. I need to wait for the 10.9 update, maybe popcap will remove rton, if so, the tool will support newton encoding.

**Comment by twinkles-twinstar** [comment]
This issue has been resolved in today's push.
