### ISSUE TITLE
Loosen Kernel Json Library

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#18]
I have added the version: 6 to the pam json, later toolkit doesn't support the conversion due to non-used properties appear. Can this be loosen in Kernel like you did with the Helper?
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/e6a1c2e7-9c4b-4069-b5e3-92799608987f)
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/20a184fd-82cf-4415-a544-5f2e0cc265de)

**Comment by twinkles-twinstar** [comment]
Strict JSON structure is the expected behavior of the Kernel and there are no plans to change this behavior.
If you need looser JSON, you need to modify `Kernel/kernel/utility/support/json.hpp`:
`line 677`: delete
`line 680`: delete
`line 681`: change to `thix_object.query_force(make_string_view(Field::name.view())).value.to(Field::value_of(that));`
