### ISSUE TITLE
Bug: reading path with more than 260 characters

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#26]
I tried to use the Kernel to write the file on my Windows OS (the path have more than 260 characters), below is the script (The directory is already existed, so it is not the bug come from me), I think you should add the prefix "\\\\?\\" for Windows machine: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170

In `Kernel/kernel/utility/file_system/file_system.hpp` line `157` make this change:
```cpp
auto file = _wfopen(cast_pointer<WCHAR>(make_null_terminated_string(StringEncoding::utf8_to_utf16(self_cast<BasicString<Character8>>(make_string(Third::fmt::format("\\\\?\\{}", make_regular_path(target).to_string().view()))))).begin()).value, cast_pointer<WCHAR>(make_null_terminated_string(StringEncoding::utf8_to_utf16(self_cast<BasicString<Character8>>(make_string_view(mode)))).begin()).value);
```

![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/a9583076-5e20-46eb-8579-e325363da4f6)
[test.zip](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/14308693/test.zip)

**Comment by twinkles-twinstar** [comment]
no error on my device. 400+- chars path:
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/37923060/706815a8-604f-4f07-b639-9b2752676c79)

**Comment by Haruma-VN** [comment]
Can it write the file on your system? For me the error 
```cpp
file != nullptr
```
still occur. When I modify the Kernel it becomes regular.

**Comment by twinkles-twinstar** [comment]
On my device, the tool can read/write long path files. Does this problem also occur in shellgui and helper?

**Comment by Haruma-VN** [comment]
For me they occur in all Shell environment. It seems like this relate to Kernel?

**Comment by twinkles-twinstar** [comment]
I tested this script and on my device, the `\\?\` prefix has no effect on reading and writing files.
It seems that Windows does not allow us to use _wfopen to create files with too long names (although the total length can exceed 260, a single name still cannot be too long).
In your screenshot, writing the file failed because `100000...` is too long; reading the file succeeded because the end of `100000...` was deleted from the file name (I guess you If you create a file through explorer, it will automatically delete the end part of the file name that is too long). If you compare carefully, you can see that the file being read and the file you wish to write are different.
As shown in the figure below, even if the `\\?\` prefix is used, the file name that is too long is still illegal (Figure 2).

![1.suc](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/37923060/564d31b5-1244-4347-8a5e-34eed0153891)
![2.fai](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/37923060/f4afba2e-e8c0-4b2f-845d-0b418cee1f98)
